//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZodiacoForm.ZodiacoServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ZodiacoServiceReference.ZodiacoWebServiceSoap")]
    public interface ZodiacoWebServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento FechaResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Fecha", ReplyAction="*")]
        ZodiacoForm.ZodiacoServiceReference.FechaResponse Fecha(ZodiacoForm.ZodiacoServiceReference.FechaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Fecha", ReplyAction="*")]
        System.Threading.Tasks.Task<ZodiacoForm.ZodiacoServiceReference.FechaResponse> FechaAsync(ZodiacoForm.ZodiacoServiceReference.FechaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FechaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Fecha", Namespace="http://tempuri.org/", Order=0)]
        public ZodiacoForm.ZodiacoServiceReference.FechaRequestBody Body;
        
        public FechaRequest() {
        }
        
        public FechaRequest(ZodiacoForm.ZodiacoServiceReference.FechaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FechaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime fecha;
        
        public FechaRequestBody() {
        }
        
        public FechaRequestBody(System.DateTime fecha) {
            this.fecha = fecha;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FechaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FechaResponse", Namespace="http://tempuri.org/", Order=0)]
        public ZodiacoForm.ZodiacoServiceReference.FechaResponseBody Body;
        
        public FechaResponse() {
        }
        
        public FechaResponse(ZodiacoForm.ZodiacoServiceReference.FechaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FechaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FechaResult;
        
        public FechaResponseBody() {
        }
        
        public FechaResponseBody(string FechaResult) {
            this.FechaResult = FechaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ZodiacoWebServiceSoapChannel : ZodiacoForm.ZodiacoServiceReference.ZodiacoWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZodiacoWebServiceSoapClient : System.ServiceModel.ClientBase<ZodiacoForm.ZodiacoServiceReference.ZodiacoWebServiceSoap>, ZodiacoForm.ZodiacoServiceReference.ZodiacoWebServiceSoap {
        
        public ZodiacoWebServiceSoapClient() {
        }
        
        public ZodiacoWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZodiacoWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZodiacoWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZodiacoWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ZodiacoForm.ZodiacoServiceReference.FechaResponse ZodiacoForm.ZodiacoServiceReference.ZodiacoWebServiceSoap.Fecha(ZodiacoForm.ZodiacoServiceReference.FechaRequest request) {
            return base.Channel.Fecha(request);
        }
        
        public string Fecha(System.DateTime fecha1) {
            ZodiacoForm.ZodiacoServiceReference.FechaRequest inValue = new ZodiacoForm.ZodiacoServiceReference.FechaRequest();
            inValue.Body = new ZodiacoForm.ZodiacoServiceReference.FechaRequestBody();
            inValue.Body.fecha = fecha1;
            ZodiacoForm.ZodiacoServiceReference.FechaResponse retVal = ((ZodiacoForm.ZodiacoServiceReference.ZodiacoWebServiceSoap)(this)).Fecha(inValue);
            return retVal.Body.FechaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ZodiacoForm.ZodiacoServiceReference.FechaResponse> ZodiacoForm.ZodiacoServiceReference.ZodiacoWebServiceSoap.FechaAsync(ZodiacoForm.ZodiacoServiceReference.FechaRequest request) {
            return base.Channel.FechaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ZodiacoForm.ZodiacoServiceReference.FechaResponse> FechaAsync(System.DateTime fecha) {
            ZodiacoForm.ZodiacoServiceReference.FechaRequest inValue = new ZodiacoForm.ZodiacoServiceReference.FechaRequest();
            inValue.Body = new ZodiacoForm.ZodiacoServiceReference.FechaRequestBody();
            inValue.Body.fecha = fecha;
            return ((ZodiacoForm.ZodiacoServiceReference.ZodiacoWebServiceSoap)(this)).FechaAsync(inValue);
        }
    }
}
