//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18449
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurpForm.CurpReferencia {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CurpReferencia.ServicioCurpSoap")]
    public interface ServicioCurpSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Generar", ReplyAction="*")]
        CurpForm.CurpReferencia.GenerarResponse Generar(CurpForm.CurpReferencia.GenerarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Generar", ReplyAction="*")]
        System.Threading.Tasks.Task<CurpForm.CurpReferencia.GenerarResponse> GenerarAsync(CurpForm.CurpReferencia.GenerarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Generar", Namespace="http://tempuri.org/", Order=0)]
        public CurpForm.CurpReferencia.GenerarRequestBody Body;
        
        public GenerarRequest() {
        }
        
        public GenerarRequest(CurpForm.CurpReferencia.GenerarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GenerarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string apaterno;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string amaterno;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string dia;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string mes;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ano;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string sexo;
        
        public GenerarRequestBody() {
        }
        
        public GenerarRequestBody(string nombre, string apaterno, string amaterno, string dia, string mes, string ano, string sexo) {
            this.nombre = nombre;
            this.apaterno = apaterno;
            this.amaterno = amaterno;
            this.dia = dia;
            this.mes = mes;
            this.ano = ano;
            this.sexo = sexo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerarResponse", Namespace="http://tempuri.org/", Order=0)]
        public CurpForm.CurpReferencia.GenerarResponseBody Body;
        
        public GenerarResponse() {
        }
        
        public GenerarResponse(CurpForm.CurpReferencia.GenerarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GenerarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GenerarResult;
        
        public GenerarResponseBody() {
        }
        
        public GenerarResponseBody(string GenerarResult) {
            this.GenerarResult = GenerarResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioCurpSoapChannel : CurpForm.CurpReferencia.ServicioCurpSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioCurpSoapClient : System.ServiceModel.ClientBase<CurpForm.CurpReferencia.ServicioCurpSoap>, CurpForm.CurpReferencia.ServicioCurpSoap {
        
        public ServicioCurpSoapClient() {
        }
        
        public ServicioCurpSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioCurpSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioCurpSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioCurpSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CurpForm.CurpReferencia.GenerarResponse CurpForm.CurpReferencia.ServicioCurpSoap.Generar(CurpForm.CurpReferencia.GenerarRequest request) {
            return base.Channel.Generar(request);
        }
        
        public string Generar(string nombre, string apaterno, string amaterno, string dia, string mes, string ano, string sexo) {
            CurpForm.CurpReferencia.GenerarRequest inValue = new CurpForm.CurpReferencia.GenerarRequest();
            inValue.Body = new CurpForm.CurpReferencia.GenerarRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.apaterno = apaterno;
            inValue.Body.amaterno = amaterno;
            inValue.Body.dia = dia;
            inValue.Body.mes = mes;
            inValue.Body.ano = ano;
            inValue.Body.sexo = sexo;
            CurpForm.CurpReferencia.GenerarResponse retVal = ((CurpForm.CurpReferencia.ServicioCurpSoap)(this)).Generar(inValue);
            return retVal.Body.GenerarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CurpForm.CurpReferencia.GenerarResponse> CurpForm.CurpReferencia.ServicioCurpSoap.GenerarAsync(CurpForm.CurpReferencia.GenerarRequest request) {
            return base.Channel.GenerarAsync(request);
        }
        
        public System.Threading.Tasks.Task<CurpForm.CurpReferencia.GenerarResponse> GenerarAsync(string nombre, string apaterno, string amaterno, string dia, string mes, string ano, string sexo) {
            CurpForm.CurpReferencia.GenerarRequest inValue = new CurpForm.CurpReferencia.GenerarRequest();
            inValue.Body = new CurpForm.CurpReferencia.GenerarRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.apaterno = apaterno;
            inValue.Body.amaterno = amaterno;
            inValue.Body.dia = dia;
            inValue.Body.mes = mes;
            inValue.Body.ano = ano;
            inValue.Body.sexo = sexo;
            return ((CurpForm.CurpReferencia.ServicioCurpSoap)(this)).GenerarAsync(inValue);
        }
    }
}
