//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18408
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormDirecciones.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ClaseIPResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClaseIP", ReplyAction="*")]
        FormDirecciones.ServiceReference1.ClaseIPResponse ClaseIP(FormDirecciones.ServiceReference1.ClaseIPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClaseIP", ReplyAction="*")]
        System.Threading.Tasks.Task<FormDirecciones.ServiceReference1.ClaseIPResponse> ClaseIPAsync(FormDirecciones.ServiceReference1.ClaseIPRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ClaseIPRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ClaseIP", Namespace="http://tempuri.org/", Order=0)]
        public FormDirecciones.ServiceReference1.ClaseIPRequestBody Body;
        
        public ClaseIPRequest() {
        }
        
        public ClaseIPRequest(FormDirecciones.ServiceReference1.ClaseIPRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ClaseIPRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ip;
        
        public ClaseIPRequestBody() {
        }
        
        public ClaseIPRequestBody(int ip) {
            this.ip = ip;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ClaseIPResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ClaseIPResponse", Namespace="http://tempuri.org/", Order=0)]
        public FormDirecciones.ServiceReference1.ClaseIPResponseBody Body;
        
        public ClaseIPResponse() {
        }
        
        public ClaseIPResponse(FormDirecciones.ServiceReference1.ClaseIPResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ClaseIPResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ClaseIPResult;
        
        public ClaseIPResponseBody() {
        }
        
        public ClaseIPResponseBody(string ClaseIPResult) {
            this.ClaseIPResult = ClaseIPResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : FormDirecciones.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<FormDirecciones.ServiceReference1.WebService1Soap>, FormDirecciones.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FormDirecciones.ServiceReference1.ClaseIPResponse FormDirecciones.ServiceReference1.WebService1Soap.ClaseIP(FormDirecciones.ServiceReference1.ClaseIPRequest request) {
            return base.Channel.ClaseIP(request);
        }
        
        public string ClaseIP(int ip) {
            FormDirecciones.ServiceReference1.ClaseIPRequest inValue = new FormDirecciones.ServiceReference1.ClaseIPRequest();
            inValue.Body = new FormDirecciones.ServiceReference1.ClaseIPRequestBody();
            inValue.Body.ip = ip;
            FormDirecciones.ServiceReference1.ClaseIPResponse retVal = ((FormDirecciones.ServiceReference1.WebService1Soap)(this)).ClaseIP(inValue);
            return retVal.Body.ClaseIPResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FormDirecciones.ServiceReference1.ClaseIPResponse> FormDirecciones.ServiceReference1.WebService1Soap.ClaseIPAsync(FormDirecciones.ServiceReference1.ClaseIPRequest request) {
            return base.Channel.ClaseIPAsync(request);
        }
        
        public System.Threading.Tasks.Task<FormDirecciones.ServiceReference1.ClaseIPResponse> ClaseIPAsync(int ip) {
            FormDirecciones.ServiceReference1.ClaseIPRequest inValue = new FormDirecciones.ServiceReference1.ClaseIPRequest();
            inValue.Body = new FormDirecciones.ServiceReference1.ClaseIPRequestBody();
            inValue.Body.ip = ip;
            return ((FormDirecciones.ServiceReference1.WebService1Soap)(this)).ClaseIPAsync(inValue);
        }
    }
}
